# Generated by Django 3.2.6 on 2021-08-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_ticket_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
