# Generated by Django 3.2.6 on 2021-09-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_auto_20210830_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='headline',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flux.ticket'),
            preserve_default=False,
        ),
    ]
