# Generated by Django 3.2.7 on 2021-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=8192),
        ),
    ]
