# Generated by Django 3.2.7 on 2021-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0010_auto_20210920_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
